// AUTO-GENERATED by daily_daughter_discovery.py — do not edit
window.WOW_ARCHIVE = [
 {
  "date": "2026-09-21",
  "topic": "Space",
  "emoji": "🪐",
  "fact": "Saturn would float on water. If you had a bathtub filled with water and dropped Saturn in... it would sit on top instead of sinking! That's because Saturn is mostly made of gas — it's lighter than water, even though it looks huge.",
  "ask": "A planet made of gas floating on water? What do you think Saturn is mostly made of?",
  "hint": "If it floats on water, it must be lighter than water. What gas is very light?",
  "trythis": "Pour oil into water and watch — oil floats too! Find other things that float and sink.",
  "kid": "Imagine a balloon filled with air — it floats on water, right? Saturn is like a GIANT balloon filled with air and other light gases, floating in a cosmic bathtub. It's so light that if you put it in water, it would bob like a beach ball!",
  "sim": "gravity-orbits.html"
 },
 {
  "date": "2026-09-23",
  "topic": "Animals",
  "emoji": "🐦",
  "fact": "Crows can remember human faces for years. If a crow doesn't like you, it will teach its children to not like you too. And if you help a crow? That crow will remember you AND tell other crows about you. They hold grudges AND friendships across generations!",
  "ask": "If a crow can hold a grudge AND teach its kids about you... do you think animals are smarter than we think?",
  "hint": "Most animals don't teach their children about specific humans. Crows do.",
  "trythis": "Next time you see a crow, try to remember its face — see if it remembers yours.",
  "kid": "Crows are like feathered detectives. They watch your face carefully — if you're mean, they'll remember. If you're kind, they'll remember AND tell their crow friends. Scientists did an experiment: they wore masks and some 'helped' the crows and some 'bothered' the crows. The baby crows grew up already knowing which mask was the bad one!",
  "sim": "food-chain.html"
 },
 {
  "date": "2026-09-24",
  "topic": "Nature",
  "emoji": "🌊",
  "fact": "There is a tiny lake in the Philippines that has more unique fish species than the entire Atlantic Ocean. Lake Taal has over 100 fish species found NOWHERE else on Earth. The whole Atlantic Ocean only has about 20 freshwater fish species total!",
  "ask": "A tiny lake has more special fish than the whole ocean. How is that possible?",
  "hint": "Islands and lakes cut off from the rest of the world create their own tiny ecosystems.",
  "trythis": "Look at a map of the Philippines. How many lakes can you find?",
  "kid": "The Philippines used to be connected to land — but the ocean rose and created islands with lakes inside them. Fish in those lakes got trapped and evolved separately over millions of years, becoming completely new species! It's like putting some fish in a bowl and leaving them for a million years — they'd become different from fish outside the bowl!",
  "sim": "water-cycle.html"
 },
 {
  "date": "2026-09-25",
  "topic": "Physics",
  "emoji": "🧪",
  "fact": "Honey never goes bad. Ever. Archaeologists opened Egyptian tombs that were 3,000 years old and found honey inside — and it was still perfectly fine to eat! The oldest honey ever found was in Georgia, about 5,500 years old. Still good!",
  "ask": "Why do you think honey lasts forever, but fruit goes bad in a few days?",
  "hint": "Think about what things need to rot — and whether honey has any of those things.",
  "trythis": "Compare honey and a slice of apple. Which one do you think has more water inside?",
  "kid": "Honey is like a tiny desert inside the jar. Bacteria (the tiny creatures that make food go yucky) need water to live and grow. Honey has almost NO water in it — it's almost all sugar. And it's also super acidic, like sour candy. Nothing bad can grow there! It's like how sour candy lasts forever but fresh fruit goes mouldy.",
  "sim": "states-of-matter.html"
 },
 {
  "date": "2026-09-26",
  "topic": "Animals",
  "emoji": "🐦",
  "fact": "Butterflies taste with their feet. When a butterfly lands on a flower, it steps on it and immediately knows if the flower has nectar (the sweet drink flowers make) or not. No tasting with a tongue needed!",
  "ask": "Why do you think tasting with feet is useful for a butterfly?",
  "hint": "Butterflies don't have hands. How else would they quickly check flowers while flying?",
  "trythis": "Look at a flower next time you're outside. How many butterflies land, check, and fly away?",
  "kid": "Imagine if every time you wanted to know if your food was yummy, you had to put your feet on it. Weird, right? But for butterflies, feet are like little taste-bud sensors. They taste chemicals on the flower — and KNOW instantly: 'This flower has nectar! Let me drink!' No licking required!",
  "sim": "food-chain.html"
 },
 {
  "date": "2026-09-27",
  "topic": "Nature",
  "emoji": "🌊",
  "fact": "Octopuses have three hearts. Two hearts pump blood to their gills (the parts that help them breathe underwater). The third heart pumps blood to the rest of the body. And their blood is BLUE — because it uses copper to carry oxygen instead of iron like ours.",
  "ask": "Why do you think an octopus needs three hearts instead of one?",
  "hint": "Think about what hearts do — and why an animal with three hearts might need them.",
  "trythis": "Draw an octopus and label where each heart might go. How would you connect them?",
  "kid": "Your heart has one job: pump blood everywhere. An octopus's body is shaped differently and moves differently — so maybe two hearts pumping to the gills is like having two people blowing up balloons, and one heart pumping to the body is like one person delivering them everywhere. And blue blood? Iron in our blood makes it red. Octopus uses copper — which turns blue when it carries oxygen, like how some pools look blue!",
  "sim": "water-cycle.html"
 },
 {
  "date": "2026-09-28",
  "topic": "Science",
  "emoji": "🔬",
  "fact": "Glass is actually a liquid — a VERY slow one. Glass atoms are arranged like a liquid (all jumbled up), not like a solid crystal. It moves so slowly that you can't see it, but over HUNDREDS of years, very old window panes become slightly thicker at the bottom!",
  "ask": "If glass is a liquid... is the window slowly dripping down? Why or why not?",
  "hint": "Slow means VERY slow. Would you see it in your whole lifetime?",
  "trythis": "Look at old glass windows in photos — the bottom is sometimes thicker.",
  "kid": "Think of honey — it flows, but so slowly you can't see it drip. Glass is like honey that flows EVEN SLOWER. Old window makers didn't make perfect glass, so the glass slowly moved over hundreds of years. That's why in very old buildings, the bottom of the window glass is thicker — the glass 'dripped' down over centuries!",
  "sim": "floating-sinking.html"
 },
 {
  "date": "2026-09-29",
  "topic": "Human Body",
  "emoji": "🫀",
  "fact": "You can't tickle yourself. Try it right now — tickle your own foot. Does it feel ticklish? Probably not! Your brain has a special part that compares what you EXPECT to feel vs what you actually feel — and because YOU know exactly where your fingers are going, it cancels out the tickle!",
  "ask": "Why do you think your brain cancels out your own touch? What would happen if it didn't?",
  "hint": "If you couldn't cancel your own touch... would everything feel like someone was poking you?",
  "trythis": "Try to tickle yourself right now. What happens?",
  "kid": "Imagine if your brain DIDN'T cancel your own touch. Your clothes would feel like someone rubbing you all day. Your feet in shoes would feel like someone poking you constantly. Your brain's 'cancel' button stops this from happening so you can focus on things OUTSIDE your body! The tickle only works when something surprises your brain — and nothing surprises you like your own hand!",
  "sim": "sound-vibrations.html"
 },
 {
  "date": "2026-09-30",
  "topic": "Human Body",
  "emoji": "🫀",
  "fact": "Your nose and ears never stop growing. Most of your body stops growing when you're an adult. But cartilage — the squishy stuff in your nose and ears — keeps growing slowly your WHOLE life. That's why old people often have bigger noses and ears than you!",
  "ask": "Why do you think nose and ears keep growing, but your arms and legs stop?",
  "hint": "Noses and ears are made of cartilage. Arms and legs are made of bone. Are they the same material?",
  "trythis": "Look at pictures of the same person when they were 20 vs 60. Can you see the difference?",
  "kid": "Your nose and ears are made of a special bendy material called cartilage — like the squishy part at the tip of your nose. This stuff never stops slowly growing. Your bones — in your arms and legs — stop when you're grown up. So an old person's ears might be twice as big as when they were 20, but their arms aren't twice as long!",
  "sim": "sound-vibrations.html"
 },
 {
  "date": "2026-10-01",
  "topic": "Science",
  "emoji": "🔬",
  "fact": "A day on Venus is LONGER than its year. Venus takes 225 Earth days to go around the Sun once. But it takes 243 Earth days to spin around once! So before Venus finishes one 'day' — sunrise to sunrise — it's already done one whole trip around the Sun.",
  "ask": "If a day is longer than a year... what does your calendar on Venus look like?",
  "hint": "Imagine: the Sun rises, and by the time it sets... you've already had a birthday.",
  "trythis": "Spin yourself slowly while walking in a circle. Count how many spins before you get back to where you started walking.",
  "kid": "On Earth, your birthday comes every 365 days (that's one trip around the Sun). On Venus, your birthday would come BEFORE you finish one day! It's like: you wake up, the Sun sets, and your friends say 'happy birthday' before the day is even over! Venus spins so slowly that it takes forever to do one spin, but it zooms around the Sun pretty fast.",
  "sim": "floating-sinking.html"
 },
 {
  "date": "2026-10-02",
  "topic": "Science",
  "emoji": "🔬",
  "fact": "Hot water can FREEZE faster than cold water. This sounds impossible, right? Scientists call it the Mpemba Effect. It was first noticed over 2,000 years ago! Nobody fully understands why it happens yet — scientists are still arguing about it!",
  "ask": "Why do you think hot water might freeze faster? What would you need to test this?",
  "hint": "Think about what happens to water when it gets hot — does anything happen to the water molecules?",
  "trythis": "Put two ice cube trays in the freezer — one with hot water, one with cold. Time them!",
  "kid": "One idea: when water is hot, the molecules move super fast. When you put it in the freezer, the fast molecules might escape as steam first — leaving less water to freeze! So there's less to cool down. But scientists aren't sure. Maybe YOU can help figure it out when you're older!",
  "sim": "floating-sinking.html"
 },
 {
  "date": "2026-10-03",
  "topic": "Science",
  "emoji": "🔬",
  "fact": "Sharks existed BEFORE trees. Sharks have been swimming in the ocean for at least 400 million years. Trees only came along about 50 million years later. Sharks survived four of the five mass extinctions on Earth — the times when most living things died!",
  "ask": "Sharks survived four mass extinctions but trees are 'new'... what does that tell you about how tough sharks are?",
  "hint": "Trees seem everywhere and permanent. But sharks were here way before them.",
  "trythis": "Draw a timeline starting 400 million years ago. Put sharks near the start. Where would trees go?",
  "kid": "Sharks are like the original survivors of Earth. When the dinosaurs died, sharks kept swimming. When huge volcanoes erupted and oceans changed, sharks kept swimming. Trees came along much later — and sharks are STILL here, still the same basic design that worked 400 million years ago. They're one of the oldest predators on Earth!",
  "sim": "floating-sinking.html"
 },
 {
  "date": "2026-10-04",
  "topic": "Human Body",
  "emoji": "🫀",
  "fact": "Your body glows in the dark. Not like a torch — but you actually make a tiny bit of light all the time. Scientists took super-sensitive photos of people sitting in completely dark rooms and caught this light! The brightest part is your face. Nobody knows exactly why yet.",
  "ask": "We can see in visible light... but what if we could see the light our own bodies make?",
  "hint": "The light your body makes is too weak for your eyes to see — but cameras can catch it.",
  "trythis": "Look at your hand under a very bright light, then suddenly cover it — do you see any faint glow as your eyes adjust?",
  "kid": "Your body is like a phone with the screen on super super dim — so dim your eyes can't see it! But scientists have special cameras that can. Every living thing glows a tiny bit. It's called bioluminescence. Fireflies use it to make light we CAN see — your body does it too, just way way dimmer!",
  "sim": "sound-vibrations.html"
 },
 {
  "date": "2026-10-05",
  "topic": "Human Body",
  "emoji": "🫀",
  "fact": "Your nose and ears never stop growing. Most of your body stops growing when you're an adult. But cartilage — the squishy stuff in your nose and ears — keeps growing slowly your WHOLE life. That's why old people often have bigger noses and ears than you!",
  "ask": "Why do you think nose and ears keep growing, but your arms and legs stop?",
  "hint": "Noses and ears are made of cartilage. Arms and legs are made of bone. Are they the same material?",
  "trythis": "Look at pictures of the same person when they were 20 vs 60. Can you see the difference?",
  "kid": "Your nose and ears are made of a special bendy material called cartilage — like the squishy part at the tip of your nose. This stuff never stops slowly growing. Your bones — in your arms and legs — stop when you're grown up. So an old person's ears might be twice as big as when they were 20, but their arms aren't twice as long!",
  "sim": "sound-vibrations.html"
 },
 {
  "date": "2026-10-06",
  "topic": "Nature",
  "emoji": "🌊",
  "fact": "There is a tiny lake in the Philippines that has more unique fish species than the entire Atlantic Ocean. Lake Taal has over 100 fish species found NOWHERE else on Earth. The whole Atlantic Ocean only has about 20 freshwater fish species total!",
  "ask": "A tiny lake has more special fish than the whole ocean. How is that possible?",
  "hint": "Islands and lakes cut off from the rest of the world create their own tiny ecosystems.",
  "trythis": "Look at a map of the Philippines. How many lakes can you find?",
  "kid": "The Philippines used to be connected to land — but the ocean rose and created islands with lakes inside them. Fish in those lakes got trapped and evolved separately over millions of years, becoming completely new species! It's like putting some fish in a bowl and leaving them for a million years — they'd become different from fish outside the bowl!",
  "sim": "water-cycle.html"
 },
 {
  "date": "2026-10-07",
  "topic": "Animals",
  "emoji": "🐦",
  "fact": "Dolphins have names for each other. Each dolphin has a unique whistle — like a name. When a dolphin wants to call another specific dolphin, it makes THAT dolphin's sound. Other dolphins answer when they hear their own name!",
  "ask": "If dolphins have names... do they talk to each other like we do?",
  "hint": "Scientists recorded dolphins repeating each other's 'names' back and forth.",
  "trythis": "If you had a signature sound instead of a name, what would yours sound like?",
  "kid": "Imagine if instead of your name, you had a special sound — like 'BEEP-BOOP-BEEP' — and everyone called you by that sound. That's how dolphins work! A mother dolphin makes her baby's sound over and over so the baby learns it. Then when they're far apart in the ocean, she calls 'BEEP-BOOP-BEEP!' and her baby knows it's her!",
  "sim": "food-chain.html"
 },
 {
  "date": "2026-10-08",
  "topic": "Animals",
  "emoji": "🐦",
  "fact": "Butterflies taste with their feet. When a butterfly lands on a flower, it steps on it and immediately knows if the flower has nectar (the sweet drink flowers make) or not. No tasting with a tongue needed!",
  "ask": "Why do you think tasting with feet is useful for a butterfly?",
  "hint": "Butterflies don't have hands. How else would they quickly check flowers while flying?",
  "trythis": "Look at a flower next time you're outside. How many butterflies land, check, and fly away?",
  "kid": "Imagine if every time you wanted to know if your food was yummy, you had to put your feet on it. Weird, right? But for butterflies, feet are like little taste-bud sensors. They taste chemicals on the flower — and KNOW instantly: 'This flower has nectar! Let me drink!' No licking required!",
  "sim": "food-chain.html"
 },
 {
  "date": "2026-10-09",
  "topic": "Science",
  "emoji": "🔬",
  "fact": "A day on Venus is LONGER than its year. Venus takes 225 Earth days to go around the Sun once. But it takes 243 Earth days to spin around once! So before Venus finishes one 'day' — sunrise to sunrise — it's already done one whole trip around the Sun.",
  "ask": "If a day is longer than a year... what does your calendar on Venus look like?",
  "hint": "Imagine: the Sun rises, and by the time it sets... you've already had a birthday.",
  "trythis": "Spin yourself slowly while walking in a circle. Count how many spins before you get back to where you started walking.",
  "kid": "On Earth, your birthday comes every 365 days (that's one trip around the Sun). On Venus, your birthday would come BEFORE you finish one day! It's like: you wake up, the Sun sets, and your friends say 'happy birthday' before the day is even over! Venus spins so slowly that it takes forever to do one spin, but it zooms around the Sun pretty fast.",
  "sim": "floating-sinking.html"
 },
 {
  "date": "2026-10-10",
  "topic": "Biology",
  "emoji": "🌳",
  "fact": "Trees talk to each other underground using fungus threads. When a big tree has extra food, it sends it through the fungus to baby trees that can't get enough sunlight yet. The baby trees say thank you by giving the fungus some of their food too. It's like a food delivery network — but underground!",
  "ask": "If trees can share food with each other... is a forest one big thing, or lots of separate things?",
  "hint": "It's a bit like the internet... but made of fungus and roots.",
  "trythis": "Next time it rains and a mushroom pops up — point and say: 'That's just the tip of something much bigger underground.'",
  "kid": "The underground fungus is like a超级 roads for food. Big trees are like big brothers — they share their lunch with smaller trees through these underground roads. And the fungus gets paid in sugar! It's like a tree marketplace — underground, silent, millions of years old.",
  "sim": "plant-growth.html"
 }
];
