// AUTO-GENERATED by daily_daughter_discovery.py — do not edit
window.WOW_ARCHIVE = [
 {
  "date": "2026-09-22",
  "topic": "Space",
  "emoji": "🪐",
  "fact": "Test fact for archive.",
  "ask": "Test ask?",
  "hint": "Test hint.",
  "trythis": "Test try.",
  "kid": "Test kid answer.",
  "sim": "gravity-orbits.html"
 }
];
